name: dan_xi
description: Maybe the best all-rounded service app for Fudan University students.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.3+37

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  dio_cookie_manager: ^2.0.0
  flutter_progress_dialog:
    git:
      url: git://github.com/kavinzhao/flutter_progress_dialog.git
      ref: master
  beautifulsoup: ^0.0.1
  quick_actions: ^0.6.0+1
  qr_flutter: ^4.0.0
  provider: ^5.0.0
  catcher: ^0.6.5
  #json_serializable: ^4.1.3
  event_bus: ^2.0.0
  flutter_platform_widgets: ^1.1.0
  flutter_timetable_view: ^0.2.0
  share: ^2.0.1
  path_provider: ^2.0.1
  screen: ^0.0.5
  flutter_sfsymbols: ^2.0.0
  flutter_email_sender: ^5.0.0
  auto_size_text: ^2.1.0
  ical: ^0.1.3
  url_launcher: ^6.0.3
  package_info_plus: ^1.0.1
  desktop_window: ^0.4.0
  firebase_core: ^1.0.4
  firebase_crashlytics: ^2.0.1
  flutter_html: ^2.0.0
  intl: ^0.17.0-nullsafety.2
  http: ^0.13.1
  dio: ^4.0.0
  crypto: ^3.0.1
  shared_preferences: ^2.0.5
  flutter_phoenix: ^1.0.0
  asn1lib: ^1.0.0
  file_picker: ^3.0.1
  flutter_tagging: ^3.0.0
  rsa_encrypt: ^2.0.0
  clipboard: ^0.1.3
  flutter_inappwebview: ^5.3.2
  permission_handler: ^7.1.0
  in_app_review: ^2.0.2
  html_editor_enhanced: ^2.1.1
  flutter_linkify: ^5.0.2
  linkify: ^4.0.0
  open_file: ^3.2.1
  dio_log: ^2.0.0
  flutter_colorpicker: 0.4.0 # Workaround a bug
  #json_annotation: ^3.1.1
  json_serializable: ^3.5.1
  photo_view: ^0.11.1
  gallery_saver: ^2.1.2

dependency_overrides:
  fluttertoast:
    git:
      url: https://github.com/ponnamkarthik/FlutterToast.git
      ref: master
  linkify:
    git:
        url: git://github.com/kavinzhao/linkify.git
        ref: master
  html: ^0.15.0

dev_dependencies:
  build_runner: ^1.11.0
  flutter_test:
    sdk: flutter

flutter_intl:
  enabled: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/graphics/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: sficonsets
      fonts:
        - asset: packages/flutter_sfsymbols/fonts/sficonsets.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages