name: dan_xi
description: Maybe the best all-rounded service app for Fudan University students.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.3.4+139

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4

  dio_cookie_manager: ^2.0.0
  flutter_progress_dialog:
    git:
      url: git://github.com/singularity-s0/flutter_progress_dialog.git
      ref: master
  xiao_mi_push_plugin:
    git:
      url: git://github.com/w568w/FlutterXiaoMiPushPlugin.git
      ref: master
  beautiful_soup_dart: ^0.2.0
  quick_actions: ^0.6.0+9
  qr_flutter: ^4.0.0
  provider: ^6.0.2
  catcher: ^0.6.9
  event_bus: ^2.0.0
  flutter_platform_widgets: ^1.12.1
  share: ^2.0.4
  path_provider: ^2.0.8
  screen_brightness: ^0.1.3
  flutter_email_sender: ^5.0.2
  auto_size_text: ^3.0.0-nullsafety.0
  ical: ^0.2.2
  url_launcher: ^6.0.18
  desktop_window: ^0.4.0
  intl: ^0.17.0-nullsafety.2
  http: ^0.13.1
  dio: ^4.0.4
  shared_preferences: ^2.0.5
  flutter_phoenix: ^1.0.0
  asn1lib: ^1.0.0
  image_picker: ^0.8.1
  clipboard: ^0.1.3
  flutter_inappwebview: ^5.3.2
  permission_handler: ^8.3.0
  in_app_review: ^2.0.2
  flutter_linkify: ^5.0.2
  linkify: ^4.0.0
  open_file: ^3.2.1
  dio_log: ^2.0.0
  json_serializable: ^6.1.3
  photo_view: ^0.13.0
  gallery_saver: ^2.1.2
  flutter_markdown: ^0.6.2
  markdown: ^4.0.0
  system_tray: ^0.0.7
  bitsdojo_window: ^0.1.1+1
  win32: ^2.3.8
  file_picker: ^4.0.0
  cached_network_image: ^3.1.0
  google_mobile_ads: ^1.0.1
  flutter_typeahead: '>=3.1.0 <4.0.0'
  collection: '>=1.15.0 <2.0.0'
  meta: '>=1.3.0 <2.0.0'
  flutter_layout_grid: ^1.0.3
  flutter_js: ^0.5.0+3
  flutter_math_fork: ^0.6.0
  platform_device_id: ^1.0.1
  uuid: ^3.0.5
  screen_capture_event: ^1.0.0+1
  otp: ^3.0.1
  lunar: ^1.2.15
  animated_text_kit: ^4.2.1
  flutter_fgbg: ^0.1.0

dependency_overrides:
  device_info_plus: ^3.2.1
  fluttertoast:
    git:
      url: git://github.com/ponnamkarthik/FlutterToast.git
      ref: master
  linkify:
    git:
      url: git://github.com/singularity-s0/linkify.git
      ref: master

dev_dependencies:
  build_runner: ^2.1.2
  pubspec_generator: ^3.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/graphics/
    - assets/texts/
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf