name: dan_xi
description: Maybe the best all-rounded service app for Fudan University students.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.4.7+344

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5

  dio_cookie_manager: ^3.0.0
  flutter_progress_dialog:
    git:
      url: https://github.com/w568w/flutter_progress_dialog.git
      ref: master
  xiao_mi_push_plugin:
    git:
      url: https://github.com/w568w/FlutterXiaoMiPushPlugin.git
      ref: master
  beautiful_soup_dart: ^0.3.0
  quick_actions: ^1.0.1
  qr_flutter: ^4.0.0
  provider: ^6.0.5
  event_bus: ^2.0.0
  share_plus: ^10.0.2
  path_provider: ^2.0.9
  screen_brightness: ^2.0.1
  flutter_email_sender: ^7.0.0
  auto_size_text: ^3.0.0
  super_sliver_list: ^0.4.0
  ical:
    git:
      url: https://github.com/Basis-Health/ical.git
      ref: main
  url_launcher: ^6.1.12
  app_links: ^6.1.3
  desktop_window: ^0.4.0
  http: ^1.0.0
  dio: ^5.4.3+1
  shared_preferences: ^2.0.15
  flutter_phoenix: ^1.0.0
  asn1lib: ^1.1.0
  image_picker: ^1.0.0
  clipboard: ^0.1.3
  # fixme: v6.2.0-beta.3 fixes issue #498, but it's still unpublished. We have to use the master branch directly.
  flutter_inappwebview:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      path: flutter_inappwebview
  permission_handler: ^11.0.1
  in_app_review: ^2.0.4
  flutter_linkify: ^6.0.0
  linkify: ^4.0.0
  open_file: ^3.5.3
  dio5_log: ^5.1.2
  json_serializable: ^6.2.0
  photo_view: ^0.15.0
  gal: ^2.1.2
  flutter_markdown: ^0.7.3
  markdown: ^7.2.2
  flutter_highlighting: ^0.9.0
  highlighting: ^0.9.0
  win32: ^5.0.2
  file_picker: ^9.0.2
  cached_network_image: ^3.2.1
  flutter_typeahead: ^5.2.0
  collection: ">=1.15.0 <2.0.0"
  meta: ">=1.3.0 <2.0.0"
  flutter_layout_grid: ^2.0.1
  # fixme: Flutter 3.29+ drops V1 embedding support, so we have to use this fork.
  flutter_js:
    git:
      url: https://github.com/chaldea-center/flutter_js.git
  flutter_math_fork: ^0.7.2
  # fixme: platform_device_id has been unmaintained since 2021, which depends on deprecated device_info package.
  # Since Flutter 3.29+ drops V1 embedding support, which device_info uses, we have to use this fork.
  platform_device_id:
    git:
      url: https://github.com/wenelsahra/platform_device_id.git
      path: platform_device_id
  uuid: ^4.3.3
  screen_capture_event: ^1.0.0+1
  otp: ^3.0.2
  lunar: ^1.2.20
  flutter_fgbg: ^0.7.0
  lazy_load_indexed_stack: ^1.0.0
  js: ^0.7.2
  nil: ^1.1.1
  flex_color_picker: ^3.2.0
  material_color_generator: ^1.1.0
  flutter_swiper_view: ^1.1.8
  mutex: ^3.0.1
  device_info_plus: ^11.0.0
  receive_intent:
    git:
      url: https://github.com/w568w/receive_intent.git

  flutter_secure_storage: ^10.0.0-beta.4
  encrypt_shared_preferences: ^0.9.8
  encrypt: any
  device_identity: ^1.0.0
  tutorial_coach_mark: ^1.2.9
  flutter_platform_widgets: ^8.0.0
  intl: any
  json_annotation: ^4.9.0
  flutter_cache_manager: any
  html: any
  cookie_jar: any
  ffi: any
  toml: ^0.16.0
  pub_semver: ^2.1.4

dependency_overrides:
  linkify:
    git:
      url: https://github.com/DanXi-Dev/linkify.git
      ref: master

dev_dependencies:
  build_runner: ^2.1.2
  pubspec_generator: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.8.7
  # below used in build.dart
  archive: ^4.0.4
  git: ^2.2.1
  path: ^1.9.0
  args: ^2.4.2

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/graphics/
    - assets/graphics/stickers/
    - assets/texts/
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
