name: dan_xi
description: Maybe the best all-rounded service app for Fudan University students.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.3.0+60

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  dio_cookie_manager: ^2.0.0
  flutter_progress_dialog:
    git:
      url: git://github.com/w568w/flutter_progress_dialog.git
      ref: master
  beautifulsoup: ^0.0.1
  quick_actions: ^0.6.0+1
  qr_flutter: ^4.0.0
  provider: ^6.0.0
  catcher: ^0.6.5
  #json_serializable: ^4.1.3
  event_bus: ^2.0.0
  flutter_platform_widgets: ^1.1.0
  share: ^2.0.1
  path_provider: ^2.0.1
  screen: ^0.0.5
  flutter_email_sender: ^5.0.0
  auto_size_text: ^2.1.0
  ical: ^0.1.3
  url_launcher: ^6.0.3
  desktop_window: ^0.4.0
  flutter_html: ^2.0.0
  intl: ^0.17.0-nullsafety.2
  http: ^0.13.1
  dio: ^4.0.0
  # crypto: ^3.0.1
  shared_preferences: ^2.0.5
  flutter_phoenix: ^1.0.0
  asn1lib: ^1.0.0
  image_picker: ^0.8.1
#  flutter_tagging: ^3.0.0
  #  rsa_encrypt: ^2.0.0
  clipboard: ^0.1.3
  flutter_inappwebview: ^5.3.2
  permission_handler: ^8.1.4+2
  in_app_review: ^2.0.2
  flutter_linkify: ^5.0.2
  linkify: ^4.0.0
  open_file: ^3.2.1
  dio_log: ^2.0.0
  json_serializable: ^3.5.1
  photo_view: ^0.12.0
  gallery_saver: ^2.1.2
  flutter_markdown: ^0.6.2
  markdown: ^4.0.0
  #  synchronized: ^3.0.0
  system_tray: ^0.0.6
  bitsdojo_window: ^0.1.1+1
  #  scrollable_positioned_list: ^0.1.10
  win32: ^2.2.5
  file_picker: ^4.0.0
  cached_network_image: ^3.1.0
  google_mobile_ads: ^0.13.4
  flutter_typeahead: '>=3.1.0 <4.0.0'
  collection: '>=1.15.0 <2.0.0'
  meta: '>=1.3.0 <2.0.0'

dependency_overrides:
  fluttertoast:
    git:
      url: git://github.com/ponnamkarthik/FlutterToast.git
      ref: master
  linkify:
    git:
        url: git://github.com/kavinzhao/linkify.git
        ref: master
  html: ^0.15.0

dev_dependencies:
  build_runner: ^1.11.0
  pubspec_generator: ^2.1.1-dev
  flutter_test:
    sdk: flutter

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/graphics/
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages