name: dan_xi
description: Maybe the best all-rounded service app for Fudan University students.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.3.11+333

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5

  dio_cookie_manager: ^2.0.0
  flutter_progress_dialog:
    git:
      url: https://github.com/Boreas618/flutter_progress_dialog.git
      ref: master
  xiao_mi_push_plugin:
    git:
      url: https://github.com/w568w/FlutterXiaoMiPushPlugin.git
      ref: master
  beautiful_soup_dart: ^0.3.0
  quick_actions: ^1.0.1
  qr_flutter: ^4.0.0
  provider: ^6.0.5
  event_bus: ^2.0.0
  flutter_platform_widgets: ^3.0.0
  share_plus: ^4.5.3
  path_provider: ^2.0.9
  screen_brightness: ^0.2.1
  flutter_email_sender: ^5.1.0
  auto_size_text: ^3.0.0
  ical:
    git:
      url: https://github.com/dartclub/ical.git
      ref: main
  url_launcher: ^6.1.7
  desktop_window: ^0.4.0
  http: ^0.13.4
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  flutter_phoenix: ^1.0.0
  asn1lib: ^1.1.0
  image_picker: ^0.8.5
  clipboard: ^0.1.3
  flutter_inappwebview: ^5.3.2
  permission_handler: ^10.2.0
  in_app_review: ^2.0.4
  flutter_linkify: ^5.0.2
  linkify: ^4.0.0
  open_file: ^3.2.1
  dio_log: ^2.0.2
  json_serializable: ^6.2.0
  photo_view: ^0.14.0
  gallery_saver: ^2.3.2
  flutter_markdown: ^0.6.10
  markdown: ^6.0.1
  system_tray:
    git:
      url: https://github.com/antler119/system_tray.git
      ref: main
  bitsdojo_window:
    git:
      url: https://github.com/DartGit-dev/bitsdojo_window.git
      path: bitsdojo_window
      ref: master
  win32: ^5.0.2
  file_picker: ^5.3.2
  cached_network_image: ^3.2.1
  flutter_typeahead: ^4.3.3
  collection: '>=1.15.0 <2.0.0'
  meta: '>=1.3.0 <2.0.0'
  flutter_layout_grid: ^2.0.1
  flutter_js: ^0.7.0
  flutter_math_fork: ^0.7.1
  platform_device_id: ^1.0.1
  uuid: ^3.0.6
  screen_capture_event: ^1.0.0+1
  otp: ^3.0.2
  lunar: ^1.2.20
  flutter_fgbg: ^0.2.0
  lazy_load_indexed_stack: ^0.1.3
  js: ^0.6.4
  nil: ^1.1.1
  flex_color_picker: ^3.1.0
  material_color_generator: ^1.1.0
  flutter_swiper_view: ^1.1.8
  mutex: ^3.0.1
  device_info_plus: ^9.0.2


dependency_overrides:
  intl: ^0.18.1
  fluttertoast:
    git:
      url: https://github.com/ponnamkarthik/FlutterToast.git
      ref: master
  linkify:
    git:
      url: https://github.com/singularity-s0/linkify.git
      ref: master
  bitsdojo_window_platform_interface:
    git:
      url: https://github.com/DartGit-dev/bitsdojo_window.git
      path: bitsdojo_window_platform_interface
      ref: master
  bitsdojo_window_windows:
    git:
      url: https://github.com/DartGit-dev/bitsdojo_window.git
      path: bitsdojo_window_windows
      ref: master
  bitsdojo_window_macos:
    git:
      url: https://github.com/DartGit-dev/bitsdojo_window.git
      path: bitsdojo_window_macos
      ref: master
  bitsdojo_window_linux:
    git:
      url: https://github.com/DartGit-dev/bitsdojo_window.git
      path: bitsdojo_window_linux
      ref: master

dev_dependencies:
  build_runner: ^2.1.2
  pubspec_generator: ^3.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/graphics/
    - assets/texts/
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
